"""adding password to user table

Revision ID: 05e9dbf05b69
Revises: e837d1b086f4
Create Date: 2020-11-07 21:32:32.183403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e9dbf05b69'
down_revision = 'e837d1b086f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=50), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'userid')
    op.drop_column('user', 'pw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pw', sa.VARCHAR(length=20), nullable=True))
    op.add_column('user', sa.Column('userid', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('user', 'password')
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
