"""empty message

Revision ID: 35b21bd90842
Revises: 53c5be0331ff
Create Date: 2020-11-18 21:31:05.818875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b21bd90842'
down_revision = '53c5be0331ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), nullable=True),
    sa.Column('followed_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='fk_followers_followed_id_user'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='fk_followers_follower_id_user')
    )
    # ### end Alembic commands ###
